### ISSUE TITLE
1.0 Release checklist

### ISSUE THREAD

**Issue by dunnkers** [dunnkers/ember-polymer#22]
For a finished version, a couple of things still have to be addressed:
- [ ] Move all logic from index.js to a file in /lib, and write tests for it.
- [ ] Test whether vulcanization was successful.
- [ ] Have auto-importer and manual-importer act independently from each other; create a wrapper file that collects the packages and processes them.
- [ ] Revise dummy tests.
- [ ] Fix issue #25
