### ISSUE TITLE
v2.0 release checklist

### ISSUE THREAD

**Issue by dunnkers** [dunnkers/ember-polymer#74]
- [x] Change vulcanize terminology to conform to polymer-bundler.
  - Deprecate using `vulcanizeOptions` in 2.x, remove in 3.x.
  - Document new options in README.
- [x] Document 1.x and 2.x releases, along with a 'changes in 2.x' section.
- [x] Remove `window.Polymer.dom = "shadow"` since it no longer does anything - shadow DOM is default now.
- [x] Convert broccoli plugin to ES6.
- [x] Fix tests accordingly to 2.0 upgrade.

**Comment by dunnkers** [comment]
Closed by 6c0ef384d80dd12eb857ab04dc4440c5561b894f, the [2.0 release](https://github.com/dunnkers/ember-polymer/releases/tag/v2.0.0)
